[package]
name = "gnum"
version = "0.1.0"
edition = "2024"
readme = "README.md"

[features]
# Experimental APIs
more_float_constants = []
float_algebraic = []
portable_simd = []

[dependencies]

[dev-dependencies]
# For benchmarking and testing
gnum = { path = "./", features = [
    "more_float_constants",
    "float_algebraic",
    "portable_simd",
] }
