[package]
name = "gnum"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Jondolf/gnum"
readme = "README.md"

[workspace]
members = ["gimd"]
resolver = "2"

[features]
default = []

# SIMD backends
wide = ["dep:wide"]
portable_simd = []

[dependencies]
wide = { version = "1.7", optional = true }

[dev-dependencies]
gnum = { path = "./", features = ["wide", "portable_simd"] }
wide = { version = "1.7" }
