[package]
name = "gimd"
version = "0.1.0"
edition = "2024"
authors = ["Joona Aalto <jondolf.dev@gmail.com>"]
description = "Generic SIMD for stable and nightly Rust"
repository = "https://github.com/Jondolf/gnum"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = [
    "simd",
    "wide",
    "portable-simd",
    "math",
    "numerics",
    "vectorization",
]
categories = ["data-structures", "mathematics", "no-std"]

[features]
default = ["std", "wide"]

# Use the standard library's math routines instead of portable approximations
std = ["gnum/std", "wide?/std"]

# SIMD backends
wide = ["dep:wide", "gnum/wide"]
portable_simd = ["gnum/portable_simd", "bytemuck?/nightly_portable_simd"]

# Optional support for external crates
bytemuck = ["dep:bytemuck"]
zerocopy = ["dep:zerocopy"]

[dependencies]
gnum = { path = "..", default-features = false }
wide = { version = "1.7", optional = true, default-features = false }
bytemuck = { version = "1", optional = true, default-features = false, features = [
    "aarch64_simd",
    "wasm_simd",
] }
zerocopy = { version = "0.8", optional = true, default-features = false, features = [
    "simd",
] }
